language: node_js
node_js:
  - "0.10"
before_install:
script: "npm test"
addons:
  postgresql: "9.3"
before_script:
  - npm install -g pg
  - npm install -g db-migrate
  - npm install -g grunt
  - npm install -g grunt-cli
  - psql -c 'create database ripple_gateway_test;' -U postgres
  - cd lib/data/ && db-migrate up
env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/ripple_gateway_test KEY=123456789
  global:
      secure: AAAAB3NzaC1yc2EAAAADAQABAAAAgQDF0u5UP+jNS0a/d5E42PIeenTklGc5QjPYIBSfqixQJAlgjlVGtXmoAvuCr0ygWY85R7/gsIdm8gojPDBfrMRE4CMq6jX3jYpASboIc1o8+ZkQ0uBnBRSXpO6KES/M7+/CQNr/4wZrcLkGTJl7/uuV5BBsdgV5L7pL3JJnaZ6tTQ==
notifications:
  email:
    false
